# Generated by Django 4.1 on 2022-12-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_media_publicaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicaciones',
            options={'ordering': ['timestamp'], 'verbose_name': 'publicacion', 'verbose_name_plural': 'publicaciones'},
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publicacion'),
        ),
    ]
